# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the diabetes_regression model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

variables:
- template: diabetes_regression-variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Test'
  displayName: 'Test'
  jobs:
  - job: 'Test'
    displayName: 'Test'
    steps:
    - task: AzureCLI@2
      inputs:
        scriptType: pscore 
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          az extension add -n azure-cli-ml
          az ml workspace create -g jenns-centraluseuap -w jenns-generate-13 --exist-ok --yes
      displayName: 'Test extension add and workspace'
